language: go
go:
- 1.11.x
env:
- GO111MODULE=on
script:
- go build src/pkg/artifactory/
deploy:
  provider: releases
  skip_cleanup: true  
  api_key:
    secure: zMPm10r-utMH4FnjHeokww
  file: "artifactrepo"
  on:
    repo: rahulgsalecha/topcount_cicd
